INSERT INTO latin_synset VALUES ('n#L5148833','bicornis',NULL,"horned animal for sacrifice");
INSERT INTO latin_synset VALUES ('r#L9232551','quandocumque',NULL,"whenever, at whatever time");
INSERT INTO latin_synset VALUES ('a#L5748007','flumineus',NULL,"of a river, river-run");
INSERT INTO latin_synset VALUES ('a#L9370351','quadrageni',NULL,"forty each");
INSERT INTO latin_synset VALUES ('a#L1967953','bimater',NULL,"having two mothers");
INSERT INTO latin_synset VALUES ('v#L6796831','tertio',NULL,"repeat three times");
INSERT INTO latin_synset VALUES ('r#L9710101','tertio',NULL,"for the third time");
INSERT INTO latin_synset VALUES ('a#L7230672','frumentarius',NULL,"concerning grain");
INSERT INTO latin_synset VALUES ('n#L2896365','frumentarius',NULL,"corn-seller");
INSERT INTO latin_synset VALUES ('n#L1832324','scaphium',NULL,"boat-shaped drinking-vessel, ewer, basin");
INSERT INTO latin_synset VALUES ('a#L2729121','venaticus',NULL,"for hunting");
INSERT INTO latin_synset VALUES ('n#L6234151','aquarius',NULL,"water-bearer");
INSERT INTO latin_synset VALUES ('n#L1103672','centuriatus',NULL,"office of centurion");
INSERT INTO latin_synset VALUES ('n#L8299018','flaminium',NULL,"office of flamen");
INSERT INTO latin_synset VALUES ('a#L6292461','spiceus',NULL,"consisting of ears of corn");
INSERT INTO latin_synset VALUES ('r#L9512563','quinquiens',NULL,"five times");
INSERT INTO latin_synset VALUES ('v#L5655422','lucubro',NULL,"work by lamp-light, work at night");
INSERT INTO latin_synset VALUES ('a#L9732380','bimaris',NULL,"situated between two seas");
INSERT INTO latin_synset VALUES ('a#L5218580','quinqueremis',NULL,"with five banks of oars");
INSERT INTO latin_synset VALUES ('n#L3510648','quinqueremis',NULL,"a galley with five banks of oars, quinquereme");
INSERT INTO latin_synset VALUES ('n#L6634388','costum',NULL,"Oriental aromatic plant");
INSERT INTO latin_synset VALUES ('n#L1457119','scorpius',NULL,"plant");
INSERT INTO latin_synset VALUES ('r#L6853365','altrinsecus',NULL,"on the other side");
INSERT INTO latin_synset VALUES ('a#L6277644','quinquageni',NULL,"fifty each");
INSERT INTO latin_synset VALUES ('a#L5990925','bicornis',NULL,"having two horns");
INSERT INTO latin_synset VALUES ('v#L1990041','intervallo',NULL,"take at intervals");
INSERT INTO latin_synset VALUES ('v#L9844714','parento',NULL,"offer a solemn sacrifice in honor of dead kindred");
INSERT INTO latin_synset VALUES ('v#L8807434','comitio',NULL,"offer sacrifice after which comitia could be held");
INSERT INTO latin_synset VALUES ('v#L5867309','nescio ignoro',NULL,"not know");
INSERT INTO latin_synset VALUES ('a#L3491224','hesternus',NULL,"of yesterday");
INSERT INTO latin_synset VALUES ('n#L8860199','accepta',NULL,"allotment, portion of land assigned to one person");
INSERT INTO latin_synset VALUES ('r#L8852050','quartum',NULL,"for the fourth time");
INSERT INTO latin_synset VALUES ('a#L6273721','publicanus',NULL,"of the public revenue");
INSERT INTO latin_synset VALUES ('n#L4429941','urna',NULL,"voting urn");
INSERT INTO latin_synset VALUES ('n#L8180314','urna',NULL,"cinerary urn");
INSERT INTO latin_synset VALUES ('a#L4145207','denarius',NULL,"containing ten each");
INSERT INTO latin_synset VALUES ('v#L4863592','umeo',NULL,"be moist, be damp, be wet");
INSERT INTO latin_synset VALUES ('v#L4022210','lito',NULL,"make an acceptable sacrifice, obtain favorable omens");
INSERT INTO latin_synset VALUES ('n#L5765884','minae',NULL,"projecting points, pinnacles");
INSERT INTO latin_synset VALUES ('r#L2145752','nominatim',NULL,"by name");
INSERT INTO latin_synset VALUES ('v#L5668495','spico',NULL,"furnish with spikes");
INSERT INTO latin_synset VALUES ('v#L8724838','spico',NULL,"provide ears");
INSERT INTO latin_synset VALUES ('n#L7234590','flamina',NULL,"wife of a flamen, priest");
INSERT INTO latin_synset VALUES ('v#L4544689','consultor',NULL,"consult oracle, astrologer");
INSERT INTO latin_synset VALUES ('n#L6869122','quadriennium',NULL,"period of four years");
INSERT INTO latin_synset VALUES ('n#L8363790','subscriptor',NULL,"signer of an accusation, joint prosecutor");
INSERT INTO latin_synset VALUES ('n#L2259344','acerra',NULL,"box or casket for incense");
INSERT INTO latin_synset VALUES ('n#L6840540','ballista',NULL,"ballista, large military engine for throwing stones and missiles");
INSERT INTO latin_synset VALUES ('a#L6689489','cenatus',NULL,"having dined, eaten");
INSERT INTO latin_synset VALUES ('a#L3064756','talaris',NULL,"of the ankle, heel");
INSERT INTO latin_synset VALUES ('a#L2584758','talaris',NULL,"reaching, stretching to the ankles");
INSERT INTO latin_synset VALUES ('n#L4529072','contortor',NULL,"twister, one who perverts");
INSERT INTO latin_synset VALUES ('n#L2563129','favea',NULL,"favorite female slave");
INSERT INTO latin_synset VALUES ('a#L8978557','praerogativus',NULL,"voting first, asked before others");
INSERT INTO latin_synset VALUES ('a#L5016672','bipennis',NULL,"with two edges, two-edged");
INSERT INTO latin_synset VALUES ('a#L8862439','bipennis',NULL,"having two wings");
INSERT INTO latin_synset VALUES ('r#L6785680','luci',NULL,"by daylight");
INSERT INTO latin_synset VALUES ('n#L9267102','nola',NULL,"a little bell");
INSERT INTO latin_synset VALUES ('v#L365821','praenuntio',NULL,"announce in advance");
INSERT INTO latin_synset VALUES ('r#L4784007','intestato',NULL,"without a will, intestate");
INSERT INTO latin_synset VALUES ('n#L3127246','temperies',NULL,"due mingling, proper mixture, tempering, temperature, temper");
INSERT INTO latin_synset VALUES ('a#L3966904','palliatus',NULL,"dressed in a pallium");
INSERT INTO latin_synset VALUES ('a#L2739321','crinalis comatorius',NULL,"of, pertaining to hair");
INSERT INTO latin_synset VALUES ('a#L5943573','crinalis',NULL,"covered with hair-like filaments");
INSERT INTO latin_synset VALUES ('a#L7994145','crinalis',NULL,"worn in the hair");
INSERT INTO latin_synset VALUES ('n#L7042128','frumentatio',NULL,"collecting of grain");
INSERT INTO latin_synset VALUES ('n#L912140','frumentatio',NULL,"providing of corn, foraging");
INSERT INTO latin_synset VALUES ('n#L7024201','lucellum',NULL,"small gain, slight profit");
INSERT INTO latin_synset VALUES ('n#L7622551','dichoreus',NULL,"double trochee, choree, metrical foot of two chorees, trochees");
INSERT INTO latin_synset VALUES ('a#L515676','cybaeus',NULL,"round-hulled, with swelling body");
INSERT INTO latin_synset VALUES ('a#L1590228','cybaeus',NULL,"transport-, merchant-, cargo-");
INSERT INTO latin_synset VALUES ('a#L8708894','profestus',NULL,"non-festival, not a holiday, common");
INSERT INTO latin_synset VALUES ('a#L6554102','gregalis',NULL,"of the herd, flock");
INSERT INTO latin_synset VALUES ('n#L7874412','nutricula',NULL,"preserver, fosterer");
INSERT INTO latin_synset VALUES ('a#L6071050','pomarius',NULL,"of fruit, of fruit trees");
INSERT INTO latin_synset VALUES ('n#L6425240','quingeni',NULL,"five hundred each");
INSERT INTO latin_synset VALUES ('n#L8942957','alauda',NULL,"legion raised by Caesar in Gaul");
INSERT INTO latin_synset VALUES ('n#L3268839','alauda',NULL,"soldiers of the legion raised by Caesar in Gaul");
INSERT INTO latin_synset VALUES ('r#L6061724','undecumque',NULL,"from any point, source, side");
INSERT INTO latin_synset VALUES ('r#L1740195','undecumque',NULL,"in every respect");
INSERT INTO latin_synset VALUES ('v#L6343554','emungo',NULL,"wipe the nose, blow the nose");
INSERT INTO latin_synset VALUES ('a#L7422635','decemviralis',NULL,"decemviral, of the decemviri");
INSERT INTO latin_synset VALUES ('r#L1461819','siquando',NULL,"if at any time");
INSERT INTO latin_synset VALUES ('v#L1902369','secubo',NULL,"sleep apart from one''s spouse or lover");
INSERT INTO latin_synset VALUES ('v#L1475110','secubo',NULL,"live alone");
INSERT INTO latin_synset VALUES ('a#L8518513','imitabilis',NULL,"that may be imitated, imitable");
INSERT INTO latin_synset VALUES ('a#L4075438','fabrilis',NULL,"of or belonging to a workman");
INSERT INTO latin_synset VALUES ('v#L6344156','subsortior',NULL,"choose a substitute by lot, substitute by lot");
INSERT INTO latin_synset VALUES ('n#L9990681','pabulator',NULL,"forager");
INSERT INTO latin_synset VALUES ('n#L2050584','lapidatio',NULL,"throwing of stones, stoning");
INSERT INTO latin_synset VALUES ('n#L7077375','octoni',NULL,"eight each, eight at a time, by eights");
INSERT INTO latin_synset VALUES ('a#L4252557','panegyricus',NULL,"of a public assembly, festival");
INSERT INTO latin_synset VALUES ('a#L7258517','salignus',NULL,"of willow, of willow-wood, willow-");
INSERT INTO latin_synset VALUES ('n#L1070927','amentum',NULL,"throwing-strap, thong, loop attached to spear for throwing");
INSERT INTO latin_synset VALUES ('v#L2434935','nauseo',NULL,"be sea-sick");
INSERT INTO latin_synset VALUES ('v#L7433238','nauseo',NULL,"feel sick");
INSERT INTO latin_synset VALUES ('a#L9183143','quantillus',NULL,"how little?");
INSERT INTO latin_synset VALUES ('v#L1584442','circummitto',NULL,"send around, to different parts");
INSERT INTO latin_synset VALUES ('v#L5474800','condecet',NULL,"it is fitting, becoming, seemly, meet");
INSERT INTO latin_synset VALUES ('r#L5186054','nisi',NULL,"if not, unless");
INSERT INTO latin_synset VALUES ('r#L2159882','nisi',NULL,"on no other condition");
INSERT INTO latin_synset VALUES ('a#L4707795','ducenti',NULL,"two hundred");
INSERT INTO latin_synset VALUES ('v#L4903786','aegreo',NULL,"be sick, ill");
INSERT INTO latin_synset VALUES ('n#L9857191','conviva',NULL,"table companion, guest");
INSERT INTO latin_synset VALUES ('n#L2281909','ferus',NULL,"wild beast, animal");
INSERT INTO latin_synset VALUES ('a#L5395230','chordus',NULL,"late-born, produced out of, late in season");
INSERT INTO latin_synset VALUES ('a#L184983','chordus',NULL,"second, aftermath");
INSERT INTO latin_synset VALUES ('v#L5111928','exsulo',NULL,"be an exile, be banished, live in exile");
INSERT INTO latin_synset VALUES ('a#L8192117','biduus',NULL,"continuing for two days, of, for two days");
INSERT INTO latin_synset VALUES ('v#L358646','sanguino',NULL,"be bloody, run with blood");
INSERT INTO latin_synset VALUES ('v#L5000799','sanguino',NULL,"be blood-thirsty, sanguinary");
INSERT INTO latin_synset VALUES ('a#L5082459','sestertius',NULL,"two and a half");
INSERT INTO latin_synset VALUES ('n#L7056451','sestertius',NULL,"sesterce");
INSERT INTO latin_synset VALUES ('v#L9989569','subsum',NULL,"be under, be behind");
INSERT INTO latin_synset VALUES ('r#L5833850','sin',NULL,"if however, if on the contrary, but if");
INSERT INTO latin_synset VALUES ('n#L2278780','contemptor',NULL,"he who disregards, a contemner, despiser");
INSERT INTO latin_synset VALUES ('r#L1545907','quamdiu',NULL,"up to the time that");
INSERT INTO latin_synset VALUES ('a#L2085992','hodiernus',NULL,"of this day, today''s");
INSERT INTO latin_synset VALUES ('v#L3658213',NULL,NULL,"announce in advance");
INSERT INTO latin_synset VALUES ('n#L1043199','candosoccus',NULL,"vine-layer");
INSERT INTO latin_synset VALUES ('v#L3166926','infulo',NULL,"adorn with a halo");
INSERT INTO latin_synset VALUES ('n#L1172704','sistrum',NULL,"a metallic rattle used by the Egyptians in celebrating the rites of Isis");
INSERT INTO latin_synset VALUES ('n#L4750040','faenisecium',NULL,"cutting of hay");
INSERT INTO latin_synset VALUES ('n#L15208','argema',NULL,"a small ulcer in the eye");
INSERT INTO latin_synset VALUES ('a#L1848620','cyaneus',NULL,"dark blue, sea-blue");
INSERT INTO latin_synset VALUES ('a#L6871299','subsuperpartiens',NULL,"(mathematics) of a number that is contained within a greater number, along with two or three
or more of its own parts");
INSERT INTO latin_synset VALUES ('a#L6594042','praeputiatus',NULL,"having the foreskin, uncircumcised");
INSERT INTO latin_synset VALUES ('a#L4328050','altipendulus',NULL,"hanging high above");
INSERT INTO latin_synset VALUES ('a#L89342','tabacinus',NULL,"of or relating to tobacco");
INSERT INTO latin_synset VALUES ('n#L9017182','eburarius',NULL,"a worker in ivory");
INSERT INTO latin_synset VALUES ('a#L1258712','praeambulus praeambulus',NULL,"walking in front");
INSERT INTO latin_synset VALUES ('a#L9564114','cruralis',NULL,"of or belonging to the legs");
INSERT INTO latin_synset VALUES ('a#L1730276','latericius',NULL,"made or consisting of bricks");
INSERT INTO latin_synset VALUES ('a#L2239867','trimenstris',NULL,"of three months");
INSERT INTO latin_synset VALUES ('n#L8456286','futtile',NULL,"a water-vessel used in sacrifices");
INSERT INTO latin_synset VALUES ('a#L9608225','discolor',NULL,"not of the same color");
INSERT INTO latin_synset VALUES ('v#L9846425','alucinor',NULL,"wander mentally");
INSERT INTO latin_synset VALUES ('a#L8545842','inausus',NULL,"not ventured, unattempted");
INSERT INTO latin_synset VALUES ('a#L4408537','inausus',NULL,"beyond daring");
INSERT INTO latin_synset VALUES ('n#L3839858','quinquevir',NULL,"a member of five-person board or commission for any official function");
INSERT INTO latin_synset VALUES ('v#L7359192','effutuo',NULL,"exhaust completely through sexual intercourse");
INSERT INTO latin_synset VALUES ('v#L784317','defetiscor',NULL,"become fatigued");
INSERT INTO latin_synset VALUES ('a#L7850433','hyacinthinus',NULL,"of or belonging to the hyacinth");
INSERT INTO latin_synset VALUES ('r#L2737297','tolutim',NULL,"at full trot");
INSERT INTO latin_synset VALUES ('a#L8166235','semitarius',NULL,"of or belonging to lanes or by-ways");
INSERT INTO latin_synset VALUES ('a#L4296392','aequidicus',NULL,"containing corresponding words or expressions");
INSERT INTO latin_synset VALUES ('n#L3410095','decemmodia',NULL,"basket holding ten modii");
INSERT INTO latin_synset VALUES ('n#L562426','confarreatio',NULL,"an ancient solemn manner of marrying among the Romans, in which was an offering of bread in the presence of the Pontifex Maximus, or Flamen Dialis, and ten witnesses");
INSERT INTO latin_synset VALUES ('n#L3101006','decotis',NULL,"a worn out toga");
INSERT INTO latin_synset VALUES ('n#L5587760','exauguratio',NULL,"the act of rendering a consecrated structure profane");
INSERT INTO latin_synset VALUES ('n#L7467243','consocrus',NULL,"a joint mother-in-law");
INSERT INTO latin_synset VALUES ('n#L545304','similago',NULL,"the finest wheat flour");
INSERT INTO latin_synset VALUES ('a#L9521203','contaminabilis',NULL,"capable of being contaminated or polluted");
INSERT INTO latin_synset VALUES ('a#L4705134','coleatus',NULL,"provided with, having or pertaining to testicles");
INSERT INTO latin_synset VALUES ('n#L8143809','catascopus',NULL,"a lookoutship, a spy-ship, a vessel sent out to reconnoitre");
INSERT INTO latin_synset VALUES ('n#L8903276','laceratrix',NULL,"she that lacerates");
INSERT INTO latin_synset VALUES ('n#L8621311','diaconandus',NULL,"deacon-elect, one who is to be made a deacon");
INSERT INTO latin_synset VALUES ('r#L2938926','sicubi',NULL,"if anywhere, wheresoever");
INSERT INTO latin_synset VALUES ('v#L9823758','interluo',NULL,"wash under, flow between");
INSERT INTO latin_synset VALUES ('n#L6551624','conparator',NULL,"a person who compares");
INSERT INTO latin_synset VALUES ('a#L8731664','quadringenarius',NULL,"of four hundred each");
INSERT INTO latin_synset VALUES ('n#L7937842','exauditor',NULL,"a person who listens carefully, hearkens to");
INSERT INTO latin_synset VALUES ('n#L1165927','axon',NULL,"a line upon the sundial, its axis");
INSERT INTO latin_synset VALUES ('n#L683412','axon',NULL,"a part of the Roman ballista");
INSERT INTO latin_synset VALUES ('n#L703153','psythium',NULL,"a wine made of the dried grapes of the psythian vine");
INSERT INTO latin_synset VALUES ('n#L3817492','psythia',NULL,"a species of genus Vitis whose dried berries are used to make wine");
INSERT INTO latin_synset VALUES ('a#L2947594','psythius',NULL,"psythian, a designation of a species of vine");
INSERT INTO latin_synset VALUES ('a#L4396792','discolius',NULL,"consisting of an iambus, pyrrhichius, and trochaeus");
INSERT INTO latin_synset VALUES ('n#L5117497','collustrium',NULL,"a corporation that procured the lustration of the fields of a district");
INSERT INTO latin_synset VALUES ('a#L5017472','bilix',NULL,"with a double thread, two-threaded");
INSERT INTO latin_synset VALUES ('n#L8013905','antithesis',NULL,"the putting of one letter for another");
INSERT INTO latin_synset VALUES ('a#L9135003','emblematicus',NULL,"relating to the production of printed emblems or devices");
INSERT INTO latin_synset VALUES ('a#L8304740','seni',NULL,"six each");
INSERT INTO latin_synset VALUES ('n#L8573853','choragium',NULL,"the place where a chorus was trained and practised");
INSERT INTO latin_synset VALUES ('n#L3538300','choragium',NULL,"the preparing and bringing out of a chorus");
INSERT INTO latin_synset VALUES ('n#L6619896','lanternarius',NULL,"a lantern-bearer");
INSERT INTO latin_synset VALUES ('a#L5438153','praeconius',NULL,"of or belonging to a public crier");
INSERT INTO latin_synset VALUES ('n#L7259259','antinomia',NULL,"opposition between two conflicting laws");
INSERT INTO latin_synset VALUES ('n#L451049','amicarius',NULL,"a person who procures a mistress for a man");
INSERT INTO latin_synset VALUES ('a#L6674382','centumgeminus',NULL,"having one hundred units or components or elements");
INSERT INTO latin_synset VALUES ('a#L265507','uterlibet',NULL,"whichever, whichsoever (of two)");
INSERT INTO latin_synset VALUES ('n#L7695515','diapente',NULL,"a medicine made of five ingredients");
INSERT INTO latin_synset VALUES ('r#L620198','pagatim',NULL,"village by village");
INSERT INTO latin_synset VALUES ('a#L9811428','commictilis',NULL,"deserving to be defiled");
INSERT INTO latin_synset VALUES ('a#L7262259','commendaticius',NULL,"commendatory, serving for commendation");
INSERT INTO latin_synset VALUES ('r#L8468699','athletice',NULL,"athletically, in the manner of an athlete");
INSERT INTO latin_synset VALUES ('a#L6930639','fanaticus',NULL,"pertaining to a temple");
INSERT INTO latin_synset VALUES ('v#L1475908',NULL,' vela_do',"set sail on a ship");
INSERT INTO latin_synset VALUES ('n#L6681955','candidarius',NULL,"a baker of white bread");
INSERT INTO latin_synset VALUES ('a#L9678317','chiragricus',NULL,"suffering from gout of the hand");
INSERT INTO latin_synset VALUES ('n#L3862856','smaris',NULL,"a small sea-fish of inferior quality");
INSERT INTO latin_synset VALUES ('a#L609516','harundifer',NULL,"reed-bearing, crowned with reeds");
INSERT INTO latin_synset VALUES ('a#L5383819','anularis',NULL,"relating to a signet-ring");
INSERT INTO latin_synset VALUES ('n#L825485','anulare',NULL,"a white color prepared from chalk and glass beads");
INSERT INTO latin_synset VALUES ('n#L2619751','conregio',NULL,"a space delimited by the physical act of drawing lines");
INSERT INTO latin_synset VALUES ('n#L1894395','derelictor',NULL,"a person who abandons");
INSERT INTO latin_synset VALUES ('n#L6893282','carminatio',NULL,"the act of cleaning and disentangling raw wool");
INSERT INTO latin_synset VALUES ('a#L2650400','impransus deprandis',NULL,"fasting");
INSERT INTO latin_synset VALUES ('a#L9945509','propitabilis',NULL,"capable of being placated or appeased");
INSERT INTO latin_synset VALUES ('a#L4705773','ingenitus',NULL,"not brought into existence by the process of reproduction");
INSERT INTO latin_synset VALUES ('n#L7104739','cynocauma',NULL,"the heat of late summer");
INSERT INTO latin_synset VALUES ('n#L816642','cabus',NULL,"a corn-measure");
INSERT INTO latin_synset VALUES ('n#L6913380','chartiaticum',NULL,"money for paper");
INSERT INTO latin_synset VALUES ('a#L204894','conchiclatus',NULL,"prepared with beans");
INSERT INTO latin_synset VALUES ('r#L7058793','fornicatim',NULL,"in the form of an arch");
INSERT INTO latin_synset VALUES ('n#L2219843','biformitas',NULL,"the quality of having a double shape");
INSERT INTO latin_synset VALUES ('a#L6974922','congialis',NULL,"holding the measure of a congius");
INSERT INTO latin_synset VALUES ('n#L6861440','congius',NULL,"a measure for liquids equivalent to an eighth part of an amphora, six sextarii, or twelve heminae");
INSERT INTO latin_synset VALUES ('n#L8839301','archisodalitas',NULL,"a religious congregation with the authority to subsume others");
INSERT INTO latin_synset VALUES ('n#L8944460','defensatrix',NULL,"she who defends");
INSERT INTO latin_synset VALUES ('n#L801681','multicia',NULL,"soft, splendid, transparent garments");
INSERT INTO latin_synset VALUES ('n#L2819033','paliurus',NULL,"a deciduous shrub native to the Mediterranean, called Jerusalem thorn, garland thorn, Christ''s thorn, or crown of thorns (Paliurus spina Christi)");
INSERT INTO latin_synset VALUES ('a#L169595','harundineus',NULL,"made of or resembling reeds");
INSERT INTO latin_synset VALUES ('a#L1407029','sesquialter',NULL,"once and a half");
INSERT INTO latin_synset VALUES ('n#L5931531','quartadecumanus',NULL,"a soldier of the fourteenth legion");
INSERT INTO latin_synset VALUES ('n#L6885971','fellatrix',NULL,"a woman who performs fellatio");
INSERT INTO latin_synset VALUES ('n#L9716608','atractylis',NULL,"a species of woolly thistle with a spiny stem and long, sharp flower head, closely related to the safflower (Carthamus lanatus)");
INSERT INTO latin_synset VALUES ('n#L9720034','collaudator',NULL,"a person who praises warmly");
INSERT INTO latin_synset VALUES ('n#L897903','diaconium',NULL,"office or position of a deacon");
INSERT INTO latin_synset VALUES ('n#L8240447','armipotentia',NULL,"strength in arms");
INSERT INTO latin_synset VALUES ('n#L3402424','diaglaucium',NULL,"a salve made from the herb glaucium");
INSERT INTO latin_synset VALUES ('n#L4346258','glaucium',NULL,"the (bluish) plant celandine (Chelidonium glaucium)");
INSERT INTO latin_synset VALUES ('n#L1510045','abneptis',NULL,"the daughter of a great-grandchild, great-great-granddaughter");
INSERT INTO latin_synset VALUES ('n#L7489850','crystallinum',NULL,"a crystalline vase");
INSERT INTO latin_synset VALUES ('n#L5552159','salutatrix',NULL,"she that salutes, visits, or pays court to");
INSERT INTO latin_synset VALUES ('a#L4289843','circumforaneus',NULL,"of or around the forum or market-place");
INSERT INTO latin_synset VALUES ('a#L5837659','circumforaneus',NULL,"that attends markets");
INSERT INTO latin_synset VALUES ('n#L2619609','tragus',NULL,"an unidentified species of fish");
INSERT INTO latin_synset VALUES ('n#L9828691','hasta hastilis',NULL,"a measure of arable land");
INSERT INTO latin_synset VALUES ('a#L8608084','cavealis',NULL,"kept in a cave or cellar");
INSERT INTO latin_synset VALUES ('v#L9760504','adstipulor',NULL,"agree to a precondition, join in a stipulation with");
INSERT INTO latin_synset VALUES ('n#L8743137','aesculetum',NULL,"an oak-forest");
INSERT INTO latin_synset VALUES ('n#L262412','bolbine',NULL,"a kind of bulbous plant");
INSERT INTO latin_synset VALUES ('n#L5712329','molossus',NULL,"a metrical foot consisting of three long syllables");
INSERT INTO latin_synset VALUES ('a#L3172500','Molossus',NULL,"of or belonging to the Molossi, Molossian");
INSERT INTO latin_synset VALUES ('a#L519089','Chalcedonius',NULL,"of Chalcedon, Chalcedonian");
INSERT INTO latin_synset VALUES ('n#L2112860','castellarius',NULL,"the superintendent of a reservoir");
INSERT INTO latin_synset VALUES ('n#L3686494','conserva',NULL,"a female fellow slave");
INSERT INTO latin_synset VALUES ('n#L2453895','conviciator',NULL,"a person who reviles or harangues");
INSERT INTO latin_synset VALUES ('n#L7506038','staphis',NULL,"a species of Delphinium, or larkspur, of the family Ranunculaceae, with short-spurred blue flowers, also known as licebane or stavesacre");
INSERT INTO latin_synset VALUES ('n#L5483000','consocia',NULL,"a female companion, consort");
INSERT INTO latin_synset VALUES ('n#L2996479','quinqueprimi',NULL,"the five principal men in a city");
INSERT INTO latin_synset VALUES ('a#L7944623','deversorius',NULL,"belonging to an inn or lodging-place, fit to lodge in");
INSERT INTO latin_synset VALUES ('a#L3323561','novercalis',NULL,"of or belonging to a step-mother");
INSERT INTO latin_synset VALUES ('n#L4066562','attractio',NULL,"a pulling together");
INSERT INTO latin_synset VALUES ('n#L9201389','avulsor',NULL,"a person who tears off");
INSERT INTO latin_synset VALUES ('a#L7404462','exsecrabilis',NULL,"that causes a curse");
INSERT INTO latin_synset VALUES ('n#L6567468','suppromus',NULL,"an assistant to the chief steward of a household");
INSERT INTO latin_synset VALUES ('n#L9241928','adneptis',NULL,"a granddaughter of a great-grandchild");
INSERT INTO latin_synset VALUES ('a#L6252966','enarmonius',NULL,"enharmonic, the technical name in Greek music of a kind of melody, in which quarter-tones predominated");
INSERT INTO latin_synset VALUES ('a#L3510487','loricatus',NULL,"fitted with a harness");
INSERT INTO latin_synset VALUES ('n#L1799944','depalator',NULL,"one who marks out the bounds");
INSERT INTO latin_synset VALUES ('n#L6737866','carduetum',NULL,"a thicket of thistles");
INSERT INTO latin_synset VALUES ('a#L8699048','astrapoplectus',NULL,"struck by lightning");
INSERT INTO latin_synset VALUES ('r#L1712360','praefinito',NULL,"in the prescribed manner");
INSERT INTO latin_synset VALUES ('a#L1756261','quotus',NULL,"of what number, how many?");
INSERT INTO latin_synset VALUES ('a#L8432824','viceni',NULL,"twenty each");
INSERT INTO latin_synset VALUES ('v#L6543929','libet',NULL,"it is pleasing, agreeable");
INSERT INTO latin_synset VALUES ('n#L6146004','apruna',NULL,"meat of the wild boar");
INSERT INTO latin_synset VALUES ('v#L3191188',NULL,'satis_ago',"have many or too many items of business to attend to");
INSERT INTO latin_synset VALUES ('v#L2817720',NULL,'satis_accipio',"accept as security or collateral");
INSERT INTO latin_synset VALUES ('a#L7343126','indissimilis',NULL,"not unlike");
INSERT INTO latin_synset VALUES ('n#L2899719','compotrix',NULL,"a female drinking companion");
INSERT INTO latin_synset VALUES ('a#L8104470','acernus',NULL,"made of consisting of (entirely or in part) of maple wood");
INSERT INTO latin_synset VALUES ('n#L3786588','cocilendrum',NULL,"an imaginary magical condiment");
INSERT INTO latin_synset VALUES ('n#L5078469','caprina',NULL,"meat of the wild goat");
INSERT INTO latin_synset VALUES ('r#L4120348','necunde',NULL,"lest from anywhere");